const express = require('express');
const { exec } = require('child_process');
const fs = require('fs');
const path = require('path');
const app = express();

app.use(express.static('public'));
app.use(express.json()); // Allow handling JSON lists of URLs

// Enable CORS for React app on port 5173
app.use((req, res, next) => {
  res.header('Access-Control-Allow-Origin', 'http://localhost:5173');
  res.header('Access-Control-Allow-Methods', 'GET, POST, OPTIONS');
  res.header('Access-Control-Allow-Headers', 'Content-Type');
  if (req.method === 'OPTIONS') {
    return res.sendStatus(200);
  }
  next();
});

// Store results in memory for the session
let scanHistory = [];

app.post('/api/scan', async (req, res) => {
    const { urls } = req.body; // Expects array ["url1", "url2"]
    scanHistory = []; // Clear previous run

    console.log(`📝 Queuing scans for: ${urls.join(', ')}`);

    // We process scans SEQUENTIALLY to avoid crashing your computer
    for (const url of urls) {
        try {
            console.log(`▶️ Scanning: ${url}`);
            await runScanner(url);
            
            // Read the result file generated by the scanner
            const resultPath = path.join(__dirname, 'scan_results_ultimate.json');
            if (fs.existsSync(resultPath)) {
                const data = JSON.parse(fs.readFileSync(resultPath));
                scanHistory.push(data);
            }
        } catch (error) {
            console.error(`❌ Failed to scan ${url}:`, error);
            scanHistory.push({ url, error: "Scan Failed" });
        }
    }

    res.json({ success: true, results: scanHistory });
});

app.get('/api/results', (req, res) => {
    res.json(scanHistory);
});

// Helper function to run the node command
function runScanner(targetUrl) {
    return new Promise((resolve, reject) => {
        console.log(`🔍 Executing: node scanner.js "${targetUrl}"`);
        // Calls your scanner.js with the URL
        exec(`node scanner.js "${targetUrl}"`, { 
            cwd: __dirname,
            maxBuffer: 10 * 1024 * 1024 // 10MB buffer for large outputs
        }, (error, stdout, stderr) => {
            if (error) {
                console.error(`❌ Scanner error for ${targetUrl}:`, error.message);
                console.error(`Exit code: ${error.code}`);
            }
            if (stderr) {
                console.error(`⚠️ Stderr for ${targetUrl}:`, stderr);
            }
            if (stdout) {
                console.log(`📊 Scanner output for ${targetUrl}:`, stdout.substring(0, 200)); // First 200 chars
            }
            // Resolve anyway so the loop continues to the next site
            resolve();
        });
    });
}

app.listen(3000, () => {
    console.log('🚀 Command Center running at http://localhost:3000');
});
